title: Lazy Theme
email: your-email@example.com
description: It is minimal and lazy!
destination: "docs"
baseurl: "/intergall"
url: ""
twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - .gitignore
  - scss