destination: "docs"
baseurl: "/intergall"
url: ""

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - .gitignore
  - scss